calls/urls.py
from django.urls import path

from calls import views

app_name = 'calls'
urlpatterns = [

    path('new_call/', views.new_call, name="new_call"),
    path('list_calls/', views.list_calls, name="list_calls"),
    path('update_call/<int:call_id>/', views.update_call, name="update_call"),
    path('delete_call/<int:call_id>/', views.delete_call, name="delete_call"),
    path('list_calls_client/<int:user_id>/', views.list_calls_client, name="list_calls_client"),
    path('update_call_client/<int:call_id>/', views.update_call_client, name="update_call_client"),
    path('new_call_client/', views.new_call_client, name="new_call_client"),
    path('list_calls_non_att/', views.list_calls_non_att, name="list_calls_non_att"),
    path('update_teammember/<int:call_id>', views.update_teammember, name="update_teammember"),
    path('list_calls_client_resolus/<int:user_id>', views.list_calls_client_resolus, name="list_calls_client_resolus"),
    path('update_note/<int:call_id>', views.update_note, name="update_note"),
    path('calls_mal_notes/', views.calls_mal_notes, name="calls_mal_notes"),


] 

intranet_phonecenter/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls import include, url 

import users
import customer
import credits
import calls
import supports

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include('users.urls', namespace='users')),
	path(r'customer/', include('customer.urls', namespace='customer')),
	path(r'credits/', include('credits.urls', namespace='credits')),
	path(r'calls/', include('calls.urls', namespace='calls')),
	path(r'supports/', include('supports.urls', namespace='supports')),
    path('', users.views.login_view),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

users/urls.py
from django.urls import path
from users import views, cbv

app_name = 'users'
urlpatterns = [
	path(r'hello/', views.hello, name="hello"),
	path('register/', views.register, name="register"),
	path('logout/', views.logout_view, name="logout"),
    path('login/', views.login_view, name="login"),
    path('myaccount/', views.myaccount, name="myaccount"),
    path('account-settings/', views.account_settings, name="account_settings"),
    path('role-attribution/', views.role_attribution, name="role_attribution"),
    path(
        'role-attribution-teammember-<int:user_id>/',
        cbv.TeamMemberCreate.as_view(),
        name="role_attribution_teammember"
        ),
    path(
        'role-attribution-customer-<int:user_id>/',
        cbv.CustomerCreate.as_view(),
        name="role_attribution_customer"
        ),

]

intranet_phonecenter/templates/base.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Intranet-Phonecenter{% endblock title %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    {% load staticfiles %}
    <script src="{% static 'js/base.js' %}"></script>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">

    {% block head_end %}{% endblock head_end %}
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">IntranetPhonecenter</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">

        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
        </ul>

        {% if user.is_authenticated %}
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'users:myaccount' %}">{{ user.get_username }}</a>
            </li>
          </ul>
          {% if user.user_type == 2 %}
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'calls:list_calls_client' user_id=user.id %}">Mes appels</a>
            </li>
          </ul>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'calls:list_calls_client_resolus' user_id=user.id %}">Noter un appel</a>
            </li>
          </ul>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'calls:new_call_client' %}">Nouvel appel</a>
            </li>
          </ul>
          {% endif %}
          {% if request.user.is_superuser %}
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'calls:new_call' %}">Nouvel appel</a>
              </li>
            </ul>
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'calls:calls_mal_notes' %}">Appels mal notés</a>
              </li>
            </ul>
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'users:role_attribution' %}">Attribuer des rôles</a>
              </li>
            </ul>
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'calls:list_calls' %}">Liste appels</a>
              </li>
            </ul>
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'calls:list_calls_non_att' %}">Appels non attribués</a>
              </li>
            </ul>
          {% endif %}
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'users:logout' %}">Déconnexion</a>
            </li>
          </ul>
        {% else %}
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'users:login' %}">Connexion</a>
            </li>
          </ul>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'users:register' %}">Inscription</a>
            </li>
          </ul>
        {% endif %}
      </div>
    </nav>

    {% block body_header %}{% endblock body_header %}
    <main role="main" class="container" style="padding-top:60px;">

      <div class="starter-template">
        {% block content %}{% endblock content %}
      </div>

    </main>


    {% block body_footer %}{% endblock body_footer %}

  </body>
</html>