calls/urls.py
from django.urls import path

from calls import views

app_name = 'calls'
urlpatterns = [

    path('new_call/', views.new_call, name="new_call"),
    path('list_calls/', views.list_calls, name="list_calls"),
    path('update_call/<int:call_id>/', views.update_call, name="update_call"),
    path('delete_call/<int:call_id>/', views.delete_call, name="delete_call"),
    path('list_calls_client/<int:user_id>/', views.list_calls_client, name="list_calls_client"),
    path('update_call_client/<int:call_id>/', views.update_call_client, name="update_call_client"),
    path('new_call_client/', views.new_call_client, name="new_call_client"),
    path('list_calls_non_att/', views.list_calls_non_att, name="list_calls_non_att"),
    path('update_teammember/<int:call_id>', views.update_teammember, name="update_teammember"),
    path('list_calls_client_resolus/<int:user_id>', views.list_calls_client_resolus, name="list_calls_client_resolus"),
    path('update_note/<int:call_id>', views.update_note, name="update_note"),
    path('calls_mal_notes/', views.calls_mal_notes, name="calls_mal_notes"),


] 

intranet_phonecenter/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls import include, url 

import users
import customer
import credits
import calls
import supports

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include('users.urls', namespace='users')),
	path(r'customer/', include('customer.urls', namespace='customer')),
	path(r'credits/', include('credits.urls', namespace='credits')),
	path(r'calls/', include('calls.urls', namespace='calls')),
	path(r'supports/', include('supports.urls', namespace='supports')),
    path('', users.views.login_view),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

users/urls.py
from django.urls import path
from users import views, cbv

app_name = 'users'
urlpatterns = [
	path(r'hello/', views.hello, name="hello"),
	path('register/', views.register, name="register"),
	path('logout/', views.logout_view, name="logout"),
    path('login/', views.login_view, name="login"),
    path('myaccount/', views.myaccount, name="myaccount"),
    path('account-settings/', views.account_settings, name="account_settings"),
    path('role-attribution/', views.role_attribution, name="role_attribution"),
    path(
        'role-attribution-teammember-<int:user_id>/',
        cbv.TeamMemberCreate.as_view(),
        name="role_attribution_teammember"
        ),
    path(
        'role-attribution-customer-<int:user_id>/',
        cbv.CustomerCreate.as_view(),
        name="role_attribution_customer"
        ),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class BaseModel(models.Model):
	created = models.DateTimeField(auto_now_add = True, verbose_name="Date de création")
	modified = models.DateTimeField(auto_now = True, verbose_name="Date de modification")

	class Meta:
		abstract = True
		ordering = ("-created", )

class UserProfile(AbstractUser, BaseModel):

	USER_TYPE_CHOICES = (
	    (1, 'teammember'),
	    (2, 'client'),
	    )

	user_type = models.PositiveSmallIntegerField(
	    choices=USER_TYPE_CHOICES,
	    default=None,
	    blank=True,
	    null=True,
	    )

	display_name = models.TextField(
	    verbose_name="Nom d'affichage",
	    default=None,
	    blank=True,
	    null=True,
	    )

	newsletter_agreement = models.BooleanField(
        verbose_name = "Recevoir des newsletter",
        help_text = "Une par semaine maximum",
        default=False,
        db_index=True,
        )

	def __str__(self):
	    if self.display_name :
	        return self.display_name
	    else:
	        return self.username

	class Meta:
	    verbose_name = "Utilisateur"
	    verbose_name_plural = "Utilisateurs"
	    ordering = ("created", )

class TeamMember(BaseModel):

    teammember = models.OneToOneField(
        UserProfile,
        on_delete=models.CASCADE,
        primary_key=True,
        )

    support_level = models.PositiveSmallIntegerField(
        default=1,
        )

    def __str__(self):
        return "%s (support_level : %d)" % (str(self.teammember), self.support_level)


class Customer(BaseModel):

    customer = models.OneToOneField(
        UserProfile,
        on_delete=models.CASCADE,
        primary_key=True,
        )

    credits = models.IntegerField(
        default=0,
        )

    def __str__(self):
        return "%s (credits : %d)" % (str(self.customer), self.credits)

users/forms.py
from django import forms

from .models import UserProfile

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class FormWithSubmit(forms.Form):
    helper = FormHelper()
    helper.add_input(Submit('submit', "Valider", css_class="btn btn-lg btn-primary btn-block bg_main"))
    helper.form_method = 'POST'

class ModelFormWithSubmit(forms.ModelForm):
    helper = FormHelper()
    helper.add_input(Submit('submit', "Valider", css_class="btn btn-lg btn-primary btn-block bg_main"))
    helper.form_method = 'POST'


class RegisterForm(FormWithSubmit):
    username = forms.CharField(
        label = "Nom d'utilisateur",
        max_length=64,
        required=True,
        )
    email = forms.EmailField(
        label = "Adresse Email",
        max_length=256,
        required=True,
        )
    raw_password = forms.CharField(
        label = "Mot de passe",
        max_length=256,
        required=True,
        help_text = "10 caractères minimums",
        widget=forms.PasswordInput(),
    )
    raw_password_confirmation = forms.CharField(
        label = "Mot de passe (confirmation)",
        max_length=256,
        required=True,
        widget=forms.PasswordInput(),
        )

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        raw_password = cleaned_data.get('raw_password')
        raw_password_confirmation = cleaned_data.get('raw_password_confirmation')
        if len(raw_password) < 10:
            raise forms.ValidationError("Le mot de passe doit faire 10 caractères minimum")
        if raw_password and raw_password_confirmation:
            if raw_password != raw_password_confirmation:
                raise forms.ValidationError("Les mots de passe ne sont pas identiques")
        try:
            UserProfile.objects.get(username=cleaned_data['username'])
        except UserProfile.DoesNotExist:
            pass
        else:
            raise forms.ValidationError("Cet utilisateur existe déjà")

        try:
            UserProfile.objects.get(email=cleaned_data['email'])
        except UserProfile.DoesNotExist:
            pass
        else:
            raise forms.ValidationError("Cet utilisateur existe déjà")

        return cleaned_data


class AccountSettingsForm(ModelFormWithSubmit):

    # Facultatif
    display_name = forms.CharField(
        label = "Nom d'affichage",
        max_length=256,
        )

    class Meta:
        model = UserProfile
        fields = ('display_name', 'newsletter_agreement', )

users/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test

from .forms import RegisterForm, AccountSettingsForm
from .models import UserProfile

# View
def hello_old(request):
    return HttpResponse("Hello World!")

def hello(request):
    return render(
        request,
        'users/hello.html',
        {
            'message': "Hello World!",
        }
    )

def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:myaccount"))
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            raw_password = form.cleaned_data['raw_password']
            user = UserProfile.objects.create_user(
                username=username,
                email=email,
                password=raw_password,
            )
            user.save()
            login(request, user)
            return HttpResponseRedirect(reverse("users:myaccount"))
    else:
        form = RegisterForm()
    return render(
        request,
        'utils/form.html',
        {
            'url_form': reverse("users:register"),
            'title': "Inscription",
            'form':form,
        }
    )

@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("users:login"))

def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:myaccount"))
    elif 'username' in request.POST and 'password' in request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if request.GET.get('next') is not None:
                return redirect(request.GET['next'])
            else:
                return HttpResponseRedirect(reverse("users:myaccount"))
        else:
            return render(
                request,
                'users/login.html',
                {
                    "auth_error": True,
                }
            )
    else:
        return render(
            request,
            'users/login.html',
            {}
        )

@login_required
def myaccount(request):
    return render(
        request,
        'users/myaccount.html',
    )

@login_required
def account_settings(request):
    if request.method == 'POST':
        form = AccountSettingsForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
    else:
        form = AccountSettingsForm(instance=request.user)
    return render(
        request,
        'utils/form.html',
        {
            'url_form': reverse("users:register"),
            'title': "Inscription",
            'form':form,
        }
    )

@user_passes_test(lambda u: u.is_superuser)
def role_attribution(request):
    users = UserProfile.objects.filter(teammember__isnull=True, customer__isnull=True).order_by("-id")
    return render(
        request,
        'users/role_attribution.html',
        {
            'users': users,
        }
    )

users/templates/users/base.html
{% extends "base.html" %}

{% block title %}Utilisateurs{% endblock title %}

users/templates/users/hello.html
{% extends "users/base.html" %}
{% block content %}
{{ message }}
{% endblock content %}

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title_html %}
    Connexion
{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
      <div class="card card-signin my-5">
        <div class="card-body">
          <h5 class="card-title text-center">Connexion</h5>
          <form class="form-signin" method="post" action="{% url 'users:login' %}">
            {% csrf_token %}
            <div class="form-label-group">
              <input type="text" name="username" class="form-control" placeholder="Nom d'utilisateur ou email" required autofocus>
              <label for="username">Nom d'utilisateur ou email</label>
            </div>
            <div class="form-label-group">
              <input type="password" name="password" class="form-control" placeholder="Mot de passe" required>
              <label for="password">Mot de passe</label>
            </div>
            <button class="btn btn-lg btn-primary btn-block bg_main" type="submit">Connexion</button>
            {% if auth_error %}
              <div class="alert alert-danger" role="alert">
                Nom d'utilisateur ou mot de passe incorrect
              </div>
            {% endif %}
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

users/templates/users/myaccount.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title_html %}
    Connexion
{% endblock %}
{% block content %}
<h2>Mon compte</h2>
<a href="{% url 'users:account_settings'%}">Paramétrer mon compte</a>
{% endblock content %} 

users/templates/users/role_attribution.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title_html %}
    Connexion
{% endblock %}
{% block content %}
    <h2>Attribution de rôle</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Username</th>
                <th scope="col">Email</th>
                <th scope="col">
                    Membre d'équipe
                </th>
                <th scope="col">
                    Client
                </th>
            </tr>
        </thead>
        <tbody>
        {% for user_role in users %}
            <tr>
                <th scope="row">{{ user_role.username }}</th>
                <td>{{ user_role.email }}</td>
                <td>
                    <a class="btn btn-primary" href="{% url 'users:role_attribution_teammember' user_id=user_role.id %}" role="button">Membre d'équipe ?</a>
                </td>
                <td>
                    <a class="btn btn-primary" href="{% url 'users:role_attribution_customer' user_id=user_role.id %}" role="button">Client ?</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %} 