calls/urls.py
from django.urls import path

from calls import views

app_name = 'calls'
urlpatterns = [

    path('new_call/', views.new_call, name="new_call"),
    path('list_calls/', views.list_calls, name="list_calls"),
    path('update_call/<int:call_id>/', views.update_call, name="update_call"),
    path('delete_call/<int:call_id>/', views.delete_call, name="delete_call"),
    path('list_calls_client/<int:user_id>/', views.list_calls_client, name="list_calls_client"),
    path('update_call_client/<int:call_id>/', views.update_call_client, name="update_call_client"),
    path('new_call_client/', views.new_call_client, name="new_call_client"),
    path('list_calls_non_att/', views.list_calls_non_att, name="list_calls_non_att"),
    path('update_teammember/<int:call_id>', views.update_teammember, name="update_teammember"),
    path('list_calls_client_resolus/<int:user_id>', views.list_calls_client_resolus, name="list_calls_client_resolus"),
    path('update_note/<int:call_id>', views.update_note, name="update_note"),
    path('calls_mal_notes/', views.calls_mal_notes, name="calls_mal_notes"),


] 

intranet_phonecenter/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls import include, url 

import users
import customer
import credits
import calls
import supports

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include('users.urls', namespace='users')),
	path(r'customer/', include('customer.urls', namespace='customer')),
	path(r'credits/', include('credits.urls', namespace='credits')),
	path(r'calls/', include('calls.urls', namespace='calls')),
	path(r'supports/', include('supports.urls', namespace='supports')),
    path('', users.views.login_view),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

calls/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

from users.models import BaseModel, UserProfile, TeamMember, Customer

class CallCategory(BaseModel):
    name = models.CharField(
        verbose_name = "Nom",
        max_length = 200,
        )
    urgent_level = models.PositiveSmallIntegerField(
        verbose_name = "Niveau d'urgence",
        help_text = "Entre 0 (bas niveau d'urgence) et 10 (urgence critique)",
        default=3,
        validators=[
            MaxValueValidator(10),
            MinValueValidator(1)
            ]
        )

    def __str__(self):
        return "%s(%d)" % (self.name, self.urgent_level)

    class Meta:
        verbose_name = "Catégorie d'appel"
        verbose_name_plural = "Catégories d'appels"

class CallTag(BaseModel):
    name = models.CharField(
        verbose_name = "Nom",
        max_length = 100,
        )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Tag d'appel"
        verbose_name_plural = "Tags d'appels"

class CallNote(BaseModel):
    name = models.CharField(
        verbose_name = "Note",
        max_length = 100,
        )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Note"
        verbose_name_plural = "Notes"

class Call(BaseModel):

    title = models.CharField(
        verbose_name="Titre",
        max_length=200,
        )

    customer = models.ForeignKey(
        Customer,
        on_delete=models.SET_NULL,
        verbose_name = "Client",
        db_index=True,
        null=True,
        blank=True,
        default=None,
        )

    teammember = models.ForeignKey(
        "users.TeamMember",
        on_delete=models.SET_NULL,
        verbose_name = "Membre d'équipe",
        db_index=True,
        null=True,
        blank=True,
        default=None,
        )

    tags = models.ManyToManyField(
        "CallTag",
        verbose_name="Tags",
        )

    note = models.CharField(
        "CallNote",
        max_length=100,
        )

    content = models.TextField(
        verbose_name="Contenu de l'appel",
        )

    solved = models.BooleanField(
        verbose_name = "Résolu",
        default=False,
        db_index=True,
        )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Appel"
        verbose_name_plural = "Appels"

calls/forms.py
from django import forms

from users.forms import ModelFormWithSubmit
from .models import Call, CallTag, CallNote


class NewCallForm(ModelFormWithSubmit):

    tags = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        queryset=CallTag.objects.all(),
        )

    class Meta:
        model = Call
        fields = ('title', 'customer', 'tags', 'content', 'solved', )

class UpdateCallForm(ModelFormWithSubmit):

    tags = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        queryset=CallTag.objects.all(),
        )

    class Meta:
        model = Call
        fields = ('title', 'customer', 'teammember', 'tags', 'content', 'solved', )


class UpdateCallFormClient(ModelFormWithSubmit):

    tags = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        queryset=CallTag.objects.all(),
        )

    note = forms.ModelChoiceField(
        widget=forms.RadioSelect,
        queryset=CallNote.objects.all(),
        )

    class Meta:
        model = Call
        fields = ('title', 'customer', 'tags', 'content', 'note' ,'solved', )


class NewCallFormClient(ModelFormWithSubmit):

    tags = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        queryset=CallTag.objects.all(),
        )

    class Meta:
        model = Call
        fields = ('title', 'tags', 'content', )


class NoteFormClient(ModelFormWithSubmit):

    note = forms.ModelChoiceField(
        widget=forms.RadioSelect,
        queryset=CallNote.objects.all(),
        )

    class Meta:
        model = Call
        fields = ('title', 'note', )

calls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import redirect
from django.db.models import Q

from .forms import NewCallForm, UpdateCallForm, UpdateCallFormClient, NewCallFormClient, NoteFormClient
from .models import Call

def is_teammember(user=None):
    if not user or user.is_anonymous:
        return False
    return user.user_type == 1


def is_customer(user=None):
    if not user or user.is_anonymous:
        return False
    return user.user_type == 2

@user_passes_test(is_teammember)
def new_call(request):
    if request.method == 'POST':
        form = NewCallForm(request.POST)
        if form.is_valid():
            form.instance.teammember = request.user.teammember
            form.save()

    else:
        form = NewCallForm()
    return render(
        request,
        'utils/form.html',
        {
            'title': "Nouvel Appel",
            'form':form,
        }
    )

@user_passes_test(is_teammember)
def list_calls(request):
    calls = Call.objects.order_by("-id")
    return render(
        request,
        'calls/calls_list.html',
        {
            'calls': calls,
        }
    )

@user_passes_test(is_teammember)
def update_call(request, call_id):
    call = Call.objects.get(id=call_id)
    if request.method == 'POST':
        form = UpdateCallForm(request.POST, instance=call)
        if form.is_valid():
            form.save()
            return redirect('../../list_calls')

    else:
        form = UpdateCallForm(instance=call)
    return render(
        request,
        'utils/form.html',
        {
            'title': "Modification d'appel",
            'form':form,
        }
    )

@user_passes_test(is_teammember)
def delete_call(request, call_id):
    call = Call.objects.get(id=call_id).delete()
    return redirect('../../list_calls')

@user_passes_test(is_customer)
def list_calls_client(request, user_id):
    calls = Call.objects.filter(customer_id=user_id).order_by("-id")
    return render(
        request,
        'calls/calls_list.html',
        {
            'calls': calls,
        }
    )

@user_passes_test(is_customer)
def update_call_client(request, call_id):
    call = Call.objects.get(id=call_id)
    if request.method == 'POST':
        form = UpdateCallFormClient(request.POST, instance=call)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("calls:list_calls"))

    else:
        form = UpdateCallFormClient(instance=call)
    return render(
        request,
        'utils/form.html',
        {
            'title': "Modification d'appel",
            'form':form,
        }
    )

@user_passes_test(is_customer)
def new_call_client(request):
    if request.method == 'POST':
        form = NewCallFormClient(request.POST)
        if form.is_valid():
            form.instance.customer = request.user.customer
            form.save()

    else:
        form = NewCallFormClient()
    return render(
        request,
        'utils/form.html',
        {
            'title': "Nouvel Appel",
            'form':form,
        }
    )

@user_passes_test(is_teammember)
def list_calls_non_att(request):
    calls = Call.objects.filter(teammember__isnull=True).order_by("-id")
    return render(
        request,
        'calls/calls_list_non_att.html',
        {
            'calls': calls,
        }
    )

@user_passes_test(is_teammember)
def update_teammember(request, call_id):
    call = Call.objects.get(id=call_id)
    call.teammember = request.user.teammember
    call.save()
    return HttpResponseRedirect(reverse("calls:list_calls"))

@user_passes_test(is_customer)
def list_calls_client_resolus(request, user_id):
    calls = Call.objects.filter(customer_id=user_id, solved=False, note='').order_by("-id")
    return render(
        request,
        'calls/calls_list_notes.html',
        {
            'calls': calls,
        }
    )

@user_passes_test(is_teammember)
def update_note(request, call_id):
    call = Call.objects.get(id=call_id)
    if request.method == 'POST':
        form = NoteFormClient(request.POST, instance=call)
        if form.is_valid():
            form.save()

    else:
        form = NoteFormClient()
    return render(
        request,
        'utils/form.html',
        {
            'title': "Noter un appel",
            'form':form,
        }
    )


def calls_mal_notes(request):
    calls = Call.objects.filter(Q(note=0) | Q(note=1) | Q(note=2) | Q(note=3)).order_by("-id")
    return render(
        request,
        'calls/calls_list_bad_notes.html',
        {
            'calls': calls,
        }
    )

calls/templates/calls/base.html
{% extends "base.html" %}

calls/templates/calls/calls_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title_html %}
    Liste des appels
{% endblock %}
{% block content %}
    <h2>Liste des appels</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Titre</th>
                <th scope="col">Contenu</th>
                <th scope="col">Date</th>
                {% if user.user_type == 2 %}
                <th scope="col">Note</th>
                {% endif %}
                {% if request.user.is_superuser %}
                <th scope="col">Team member</th>
                {% endif %}
                <th scope="col">Résolu</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
        {% for list_calls in calls %}
            <tr>
                <th scope="row">{{ list_calls.title }}</th>
                <th scope="row">{{ list_calls.content }}</th>
                <th scope="row">{{ list_calls.created }}</th>
                {% if user.user_type == 2 %}
                <th scope="col">{{ list_calls.note }}</th>
                {% endif %}
                {% if request.user.is_superuser %}
                <th scope="col">{{ list_calls.teammember }}</th>
                {% endif %}
                <th scope="row">{{ list_calls.solved }}</th>
                {% if request.user.is_superuser %}
                <td>
                    <a class="btn btn-primary" href="{% url 'calls:update_call' call_id=list_calls.id %}" role="button">Edit l'appel</a>
                </td>
                <td>
                    <a class="btn btn-primary" href="{% url 'calls:delete_call' call_id=list_calls.id %}" role="button">Supprimer</a>
                </td>
                {% endif %}
                {% if user.user_type == 2 %}
                <td>
                    <a class="btn btn-primary" href="{% url 'calls:update_call_client' call_id=list_calls.id %}" role="button">Edit l'appel</a>
                </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %} 

calls/templates/calls/calls_list_bad_notes.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title_html %}
    Liste des appels
{% endblock %}
{% block content %}
    <h2>Liste des appels non attribués</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Titre</th>
                <th scope="col">Contenu</th>
                <th scope="col">Date</th>
                <th scope="col">Note</th>
            </tr>
        </thead>
        <tbody>
        {% for list_calls in calls %}
            <tr>
                <th scope="row">{{ list_calls.title }}</th>
                <th scope="row">{{ list_calls.content }}</th>
                <th scope="row">{{ list_calls.created }}</th>
                <th scope="row">{{ list_calls.note }}</th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %} 

calls/templates/calls/calls_list_non_att.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title_html %}
    Liste des appels
{% endblock %}
{% block content %}
    <h2>Liste des appels</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Titre</th>
                <th scope="col">Contenu</th>
                <th scope="col">Date</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
        {% for list_calls in calls %}
            <tr>
                <th scope="row">{{ list_calls.title }}</th>
                <th scope="row">{{ list_calls.content }}</th>
                <th scope="row">{{ list_calls.created }}</th>
                <td>
                    <a class="btn btn-primary" href="{% url 'calls:update_teammember' call_id=list_calls.id %}" role="button">M'attribuer ce call</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %} 

calls/templates/calls/calls_list_notes.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title_html %}
    Liste des appels
{% endblock %}
{% block content %}
    <h2>Liste des appels résolus non notés</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Titre</th>
                <th scope="col">Contenu</th>
                <th scope="col">Date</th>
                <th scope="col">Note</th>
            </tr>
        </thead>
        <tbody>
        {% for list_calls in calls %}
            <tr>
                <th scope="row">{{ list_calls.title }}</th>
                <th scope="row">{{ list_calls.content }}</th>
                <th scope="row">{{ list_calls.created }}</th>
                <td>
                    <a class="btn btn-primary" href="{% url 'calls:update_note' call_id=list_calls.id %}" role="button">Noter</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %} 